name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          mkdir -p ./build &&
          docker build --tag pulseaudio-win32 --build-arg "PAW32_VERSION=$(echo "$(git describe --always --tags)" | sed -e "s/^v//g")" ./src &&
          docker save pulseaudio-win32 > imagesave.tar
      - name: Upload (imagesave.tar)
        uses: actions/upload-artifact@v4
        with:
          name: imagesave.tar
          path: imagesave.tar

